version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohort1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-03-01.csv

  generate_cohort2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-09-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-09-01.csv

  run_model:
    run: stata-mp:latest analysis/model.do
    needs: [generate_cohort1]
    outputs:
      moderately_sensitive:
        log: logs/model.log

