version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohort1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-03-01.csv

  generate_cohort2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-09-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-09-01.csv

  clean:
    run: stata-mp:latest analysis/001_clean_input_data.do
    needs: [generate_cohort1, generate_cohort2]
    outputs:
      moderately_sensitive:
        log: logs/001_clean_input_data.log

  create_analysis:
    run: stata-mp:latest analysis/002_create_ld_analysis_dataset.do
    needs: [clean]
    outputs:
      moderately_sensitive:
        log: logs/002_create_ld_analysis_dataset.log

  describe_cohort:
    run: stata-mp:latest analysis/AL001_describe_cohort.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL001_describe_cohort.log

  cox_regression:
    run: stata-mp:latest analysis/AL003_cox_regression.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL003_cox_regression.log
        model: output/output_hrs_main.out
        model2: output/output_rates.out

