version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_cohort1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-03-01.csv

  generate_cohort2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-09-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-09-01.csv

  clean:
    run: stata-mp:latest analysis/001_clean_input_data.do
    needs: [generate_cohort1, generate_cohort2]
    outputs:
     highly_sensitive:
        clean1: analysis/data_base_cohort1.dta
        clean2: analysis/data_base_cohort2.dta

  create_analysis:
    run: stata-mp:latest analysis/002_create_ld_analysis_dataset.do
    needs: [clean]
    outputs:
     highly_sensitive:
        an_data1: analysis/data_ldanalysis_cohort1.dta
        an_data2: analysis/data_ldanalysis_cohort2.dta


  create_analysis_ar:
    run: stata-mp:latest analysis/003_create_ar_analysis_dataset.do
    needs: [clean]
    outputs:
     highly_sensitive:
        an_data1: analysis/data_aranalysis_cohort1.dta
        an_data2: analysis/data_aranalysis_cohort2.dta


  describe_cohort:
    run: stata-mp:latest analysis/AL001_describe_cohort.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL001_describe_cohort.log

  tabulate_cohort:
    run: stata-mp:latest analysis/AL002_tabulate_cohort_descriptives.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL002_tabulate_cohort_descriptives.log
        model: output/basetable1.txt


  describe_cohort_ar:
    run: stata-mp:latest analysis/AAR001_describe_cohort.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_describe_cohort.log

  tabulate_cohort_ar:
    run: stata-mp:latest analysis/AR001b_tabulate_cohort_descriptives.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AR001b_tabulate_cohort_descriptives.log
        model: output/basetable1_ar.txt


  cox_regression_child:
    run: stata-mp:latest analysis/AL005_cox_regression_child.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL005_cox_regression_child.log
        hrs_child: output/output_hrs_main_child.out
        rates_child: output/output_rates_child.out

  cumulative_incidence:
    run: stata-mp:latest analysis/AL003_cumulative_incidence.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL003_cumulative_incidence.log
        graph1: output/cumincidence_coviddeath.svg
        graph2: output/cumincidence_composite.svg

  cox_lda1:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 covidadmission ldr
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_covidadmission_ldr.log
        hrs: output/ldcox_wave1_covidadmission_ldr.out

  cox_lda2:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 covidadmission ldr
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_covidadmission_ldr.log
        hrs: output/ldcox_wave2_covidadmission_ldr.out

  cox_lda3:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 covidadmission ldr_cat
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_covidadmission_ldr_cat.log
        hrs: output/ldcox_wave1_covidadmission_ldr_cat.out

  cox_lda4:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 covidadmission ldr_cat
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_covidadmission_ldr_cat.log
        hrs: output/ldcox_wave2_covidadmission_ldr_cat.out

  cox_lda5:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 covidadmission ldr_carecat
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_covidadmission_ldr_carecat.log
        hrs: output/ldcox_wave1_covidadmission_ldr_carecat.out

  cox_lda6:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 covidadmission ldr_carecat
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_covidadmission_ldr_carecat.log
        hrs: output/ldcox_wave2_covidadmission_ldr_carecat.out

  cox_lda7:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 covidadmission ds
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_covidadmission_ds.log
        hrs: output/ldcox_wave1_covidadmission_ds.out

  cox_lda8:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 covidadmission ds
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_covidadmission_ds.log
        hrs: output/ldcox_wave2_covidadmission_ds.out

  cox_lda9:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 covidadmission cp
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_covidadmission_cp.log
        hrs: output/ldcox_wave1_covidadmission_cp.out

  cox_lda10:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 covidadmission cp
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_covidadmission_cp.log
        hrs: output/ldcox_wave2_covidadmission_cp.out

  cox_lda11:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 covidadmission ldr_group
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_covidadmission_ldr_group.log
        hrs: output/ldcox_wave1_covidadmission_ldr_group.out

  cox_lda12:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 covidadmission ldr_group
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_covidadmission_ldr_group.log
        hrs: output/ldcox_wave2_covidadmission_ldr_group.out


  cox_ldd1:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 coviddeath ldr
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_coviddeath_ldr.log
        hrs: output/ldcox_wave1_coviddeath_ldr.out

  cox_ldd2:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 coviddeath ldr
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_coviddeath_ldr.log
        hrs: output/ldcox_wave2_coviddeath_ldr.out

  cox_ldd3:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 coviddeath ldr_cat
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_coviddeath_ldr_cat.log
        hrs: output/ldcox_wave1_coviddeath_ldr_cat.out

  cox_ldd4:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 coviddeath ldr_cat
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_coviddeath_ldr_cat.log
        hrs: output/ldcox_wave2_coviddeath_ldr_cat.out

  cox_ldd5:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 coviddeath ldr_carecat
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_coviddeath_ldr_carecat.log
        hrs: output/ldcox_wave1_coviddeath_ldr_carecat.out

  cox_ldd6:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 coviddeath ldr_carecat
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_coviddeath_ldr_carecat.log
        hrs: output/ldcox_wave2_coviddeath_ldr_carecat.out

  cox_ldd7:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 coviddeath ds
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_coviddeath_ds.log
        hrs: output/ldcox_wave1_coviddeath_ds.out

  cox_ldd8:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 coviddeath ds
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_coviddeath_ds.log
        hrs: output/ldcox_wave2_coviddeath_ds.out

  cox_ldd9:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 coviddeath cp
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_coviddeath_cp.log
        hrs: output/ldcox_wave1_coviddeath_cp.out

  cox_ldd10:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 coviddeath cp
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_coviddeath_cp.log
        hrs: output/ldcox_wave2_coviddeath_cp.out

  cox_ldd11:
    run: stata-mp:latest analysis/AL004_cox_regression.do 1 coviddeath ldr_group
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave1_coviddeath_ldr_group.log
        hrs: output/ldcox_wave1_coviddeath_ldr_group.out

  cox_ldd12:
    run: stata-mp:latest analysis/AL004_cox_regression.do 2 coviddeath ldr_group
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_wave2_coviddeath_ldr_group.log
        hrs: output/ldcox_wave2_coviddeath_ldr_group.out


  cox_ar1:
    run: stata-mp:latest analysis/AAR001_cox_regression.do 1 covidadmission
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_cox_regression_wave1_covidadmission.log
        hrs: output/hr_wave1_male*_covidadmission.txt

  cox_ar2:
    run: stata-mp:latest analysis/AAR001_cox_regression.do 2 covidadmission
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_cox_regression_wave2_covidadmission.log
        hrs: output/hr_wave2_male*_covidadmission.txt

  cox_ar3:
    run: stata-mp:latest analysis/AAR001_cox_regression.do 1 coviddeath
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_cox_regression_wave1_coviddeath.log
        hrs: output/hr_wave1_male*_coviddeath.txt

  cox_ar4:
    run: stata-mp:latest analysis/AAR001_cox_regression.do 2 coviddeath
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_cox_regression_wave2_coviddeath.log
        hrs: output/hr_wave2_male*_coviddeath.txt


  ar_1:
    run: stata-mp:latest analysis/AAR002_risk_by_age.do 1 0 covidadmission
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_risk_by_age_wave1_male0_covidadmission.log
        absrisk: output/ar_wave1_male0_covidadmission.out
        graph: output/ar_wave1_male0_covidadmission.svg

  ar_2:
    run: stata-mp:latest analysis/AAR002_risk_by_age.do 1 1 covidadmission
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_risk_by_age_wave1_male1_covidadmission.log
        absrisk: output/ar_wave1_male1_covidadmission.out
        graph: output/ar_wave1_male1_covidadmission.svg

  ar_3:
    run: stata-mp:latest analysis/AAR002_risk_by_age.do 2 0 covidadmission
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_risk_by_age_wave2_male0_covidadmission.log
        absrisk: output/ar_wave2_male0_covidadmission.out
        graph: output/ar_wave2_male0_covidadmission.svg

  ar_4:
    run: stata-mp:latest analysis/AAR002_risk_by_age.do 2 1 covidadmission
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_risk_by_age_wave2_male1_covidadmission.log
        absrisk: output/ar_wave2_male1_covidadmission.out
        graph: output/ar_wave2_male1_covidadmission.svg

  ar_5:
    run: stata-mp:latest analysis/AAR002_risk_by_age.do 1 0 coviddeath
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_risk_by_age_wave1_male0_coviddeath.log
        absrisk: output/ar_wave1_male0_coviddeath.out
        graph: output/ar_wave1_male0_coviddeath.svg

  ar_6:
    run: stata-mp:latest analysis/AAR002_risk_by_age.do 1 1 coviddeath
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_risk_by_age_wave1_male1_coviddeath.log
        absrisk: output/ar_wave1_male1_coviddeath.out
        graph: output/ar_wave1_male1_coviddeath.svg

  ar_7:
    run: stata-mp:latest analysis/AAR002_risk_by_age.do 2 0 coviddeath
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_risk_by_age_wave2_male0_coviddeath.log
        absrisk: output/ar_wave2_male0_coviddeath.out
        graph: output/ar_wave2_male0_coviddeath.svg

  ar_8:
    run: stata-mp:latest analysis/AAR002_risk_by_age.do 2 1 coviddeath
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_risk_by_age_wave2_male1_coviddeath.log
        absrisk: output/ar_wave2_male1_coviddeath.out
        graph: output/ar_wave2_male1_coviddeath.svg
