version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohort1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-03-01.csv

  generate_cohort2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-09-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-09-01.csv

  clean:
    run: stata-mp:latest analysis/001_clean_input_data.do
    needs: [generate_cohort1, generate_cohort2]
    outputs:
      moderately_sensitive:
        log: logs/001_clean_input_data.log

  create_analysis:
    run: stata-mp:latest analysis/002_create_ld_analysis_dataset.do
    needs: [clean]
    outputs:
      moderately_sensitive:
        log: logs/002_create_ld_analysis_dataset.log

  describe_cohort:
    run: stata-mp:latest analysis/AL001_describe_cohort.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL001_describe_cohort.log

  tabulate_cohort:
    run: stata-mp:latest analysis/AL002_tabulate_cohort_descriptives.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL002_tabulate_cohort_descriptives.log
        model: output/basetable1.txt
 
  cox_regression:
    run: stata-mp:latest analysis/AL003_cox_regression.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL003_cox_regression.log
        hrs_adult: output/output_hrs_main.out
        rates_adult: output/output_rates.out

  cox_regression_child:
    run: stata-mp:latest analysis/AL004_cox_regression_child.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression_child.log
        hrs_child: output/output_hrs_main_child.out
        rates_child: output/output_rates_child.out
