version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohort1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-03-01.csv

  generate_cohort2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-09-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-09-01.csv

  clean:
    run: stata-mp:latest analysis/001_clean_input_data.do
    needs: [generate_cohort1, generate_cohort2]
    outputs:
     highly_sensitive:
        clean1: analysis/data_base_cohort1.dta
        clean2: analysis/data_base_cohort2.dta

  create_analysis:
    run: stata-mp:latest analysis/002_create_ld_analysis_dataset.do
    needs: [clean]
    outputs:
     highly_sensitive:
        an_data1: analysis/data_ldanalysis_cohort1.dta
        an_data2: analysis/data_ldanalysis_cohort2.dta


  create_analysis_ar:
    run: stata-mp:latest analysis/003_create_ar_analysis_dataset.do
    needs: [clean]
    outputs:
     highly_sensitive:
        an_data1: analysis/data_aranalysis_cohort1.dta
        an_data2: analysis/data_aranalysis_cohort2.dta


  describe_cohort:
    run: stata-mp:latest analysis/AL001_describe_cohort.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL001_describe_cohort.log

  tabulate_cohort:
    run: stata-mp:latest analysis/AL002_tabulate_cohort_descriptives.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL002_tabulate_cohort_descriptives.log
        model: output/basetable1.txt

  cox_regression:
    run: stata-mp:latest analysis/AL004_cox_regression.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_cox_regression.log
        hrs_adult: output/output_hrs_main.out
        rates_adult: output/output_rates.out

  cox_regression_child:
    run: stata-mp:latest analysis/AL005_cox_regression_child.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL005_cox_regression_child.log
        hrs_child: output/output_hrs_main_child.out
        rates_child: output/output_rates_child.out

  cumulative_incidence:
    run: stata-mp:latest analysis/AL003_cumulative_incidence.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL003_cumulative_incidence.log
        graph1: output/cumincidence_coviddeath.svg
        graph2: output/cumincidence_composite.svg

  cox_regression1:
    run: stata-mp:latest analysis/AL004_1_cox_regression.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_1_cox_regression.log
        hrs_adult: output/output_hrs_main_2_coviddeath_ldr_group.out
        rates_adult: output/output_rates_2_coviddeath_ldr_group.out

  cox_regression2:
    run: stata-mp:latest analysis/AL004_2_cox_regression.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_2_cox_regression.log
        hrs_adult: output/output_hrs_main_2_covidadmission_ldr_group.out
        rates_adult: output/output_rates_2_covidadmission_ldr_group.out

  cox_regression3:
    run: stata-mp:latest analysis/AL004_3_cox_regression.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_3_cox_regression.log
        hrs_adult: output/output_hrs_main_1_coviddeath_ldr_group.out
        rates_adult: output/output_rates_1_coviddeath_ldr_group.out

  cox_regression4:
    run: stata-mp:latest analysis/AL004_4_cox_regression.do
    needs: [create_analysis]
    outputs:
      moderately_sensitive:
        log: logs/AL004_4_cox_regression.log
        hrs_adult: output/output_hrs_main_1_covidadmission_ldr_group.out
        rates_adult: output/output_rates_1_covidadmission_ldr_group.out4

  cox_regression3_ar:
    run: stata-mp:latest analysis/AAR001_3_cox_regression.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_3_cox_regression.log
        hrfemale: output/hr_coviddeath_wave1_male0.txt
        hrmale: output/hr_coviddeath_wave1_male1.txt

  cox_regression4_ar:
    run: stata-mp:latest analysis/AAR001_4_cox_regression.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_4_cox_regression.log
        hrfemale: output/hr_coviddeath_wave2_male0.txt
        hrmale: output/hr_coviddeath_wave2_male1.txt

  cox_regression1_ar:
    run: stata-mp:latest analysis/AAR001_1_cox_regression.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_1_cox_regression.log
        hrfemale: output/hr_covidadmission_wave1_male0.txt
        hrmale: output/hr_covidadmission_wave1_male1.txt

  cox_regression2_ar:
    run: stata-mp:latest analysis/AAR001_2_cox_regression.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR001_2_cox_regression.log
        hrfemale: output/hr_covidadmission_wave2_male0.txt
        hrmale: output/hr_covidadmission_wave2_male1.txt


  ar_1:
    run: stata-mp:latest analysis/AAR002_1_risk_by_age.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_1_risk_by_age.log
        arfemale: output/ar_wave1_male0_covidadmission.out
        armale: output/ar_wave1_male1_covidadmission.out
        garfemale: output/ar_wave1_male0_covidadmission.svg
        garmale: output/ar_wave1_male1_covidadmission.svg

  ar_2:
    run: stata-mp:latest analysis/AAR002_2_risk_by_age.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_2_risk_by_age.log
        arfemale: output/ar_wave2_male0_covidadmission.out
        armale: output/ar_wave2_male1_covidadmission.out
        garfemale: output/ar_wave2_male0_covidadmission.svg
        garmale: output/ar_wave2_male1_covidadmission.svg

  ar_3:
    run: stata-mp:latest analysis/AAR002_3_risk_by_age.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_3_risk_by_age.log
        arfemale: output/ar_wave1_male0_coviddeath.out
        armale: output/ar_wave1_male1_coviddeath.out
        garfemale: output/ar_wave1_male0_coviddeath.svg
        garmale: output/ar_wave1_male1_coviddeath.svg

  ar_4:
    run: stata-mp:latest analysis/AAR002_4_risk_by_age.do
    needs: [create_analysis_ar]
    outputs:
      moderately_sensitive:
        log: logs/AAR002_4_risk_by_age.log
        arfemale: output/ar_wave2_male0_coviddeath.out
        armale: output/ar_wave2_male1_coviddeath.out
        garfemale: output/ar_wave2_male0_coviddeathn.svg
        garmale: output/ar_wave2_male1_coviddeath.svg
